#!/bin/sh

notmuch_config="$HOME/mail-config/common-mail-config/notmuch/.notmuch-config"
alias notmuchc='notmuch --config="$notmuch_config"'

notmuchc tag -new +inbox +unread -- tag:new

notmuchc tag +gmail -- 'not tag:gmail'

notmuchc tag +sent -inbox -unread -- 'from:gokul2411s and tag:gmail'

